version: '3.8'

networks:
  mynet:
    driver: bridge

volumes:
  db_data:

services:

  dbrelations:
    image: ion21/dbrelations:v2
    networks:
      - mynet
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      JAVA_OPTIONS: -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

