spring:
  application:
    name: dbrelations
  datasource:
    url: jdbc:mysql://localhost:3306/relations_db?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto:  update
      enable_lazy_load_no_trans: true
    properties:
      hibernate-dialect: org.hibernate.dialect.MySQL5Dialect
      hibernate.format_sql: true
    show-sql: true
